- platform: bayesian
  prior: 0.33
  name: "Gaby Sleeping Bayesian"
  probability_threshold: 0.85
  observations:
    - entity_id: "person.gaby"
      prob_given_true: 0.97
      prob_given_false: 0.5
      platform: "state"
      to_state: "home"
    - prob_given_true: 0.03
      prob_given_false: 0.5
      platform: "template"
      value_template: '{{ states("person.gaby") != "home" }}'
    - entity_id: "light.bedroom_1"
      prob_given_true: 0.01
      prob_given_false: 0.1
      platform: "state"
      to_state: "on"
    - entity_id: "light.bedroom_1"
      prob_given_true: 0.95
      prob_given_false: 0.45
      platform: "state"
      to_state: "off"
    - entity_id: "light.bedroom1"
      platform: state
      to_state: "unavailable"
      prob_given_true: 0.04
      prob_given_false: 0.45
    - prob_given_true: 0.9
      prob_given_false: 0.4
      platform: "template"
      value_template: >
        {% set locked_state = states.binary_sensor.gaby_honor_device_locked %}
        {% set bump = now() %}
        {{
          locked_state and locked_state.state == 'on' and (
            as_timestamp(now())
            - as_timestamp(locked_state.last_changed)
          ) > 900
        }}
    - prob_given_true: 0.1
      prob_given_false: 0.6
      platform: "template"
      value_template: >
        {% set locked_state = states.binary_sensor.gaby_honor_device_locked %}
        {% set bump = now() %}
        {{
          not (locked_state and locked_state.state == 'on' and (
            as_timestamp(now())
            - as_timestamp(locked_state.last_changed)
          ) > 900)
        }}
    - entity_id: "sensor.gaby_honor_sleep_confidence"
      prob_given_true: 0.90
      prob_given_false: 0.10
      platform: "numeric_state"
      above: 80
    - entity_id: "sensor.gaby_honor_sleep_confidence"
      prob_given_true: 0.10
      platform: "numeric_state"
      below: 20
    - platform: template
      value_template: {{ today_at("10:00") < now() and now() < today_at("22:00") }}
      prob_given_true: 0.1
      prob_given_false: 0.8
    - platform: template
      value_template: {{ not (today_at("10:00") < now() and now() < today_at("22:00")) }}
      prob_given_true: 0.9
      prob_given_false: 0.2

- platform: bayesian
  prior: 0.33
  name: "Charles Sleeping Bayesian"
  probability_threshold: 0.85
  observations:
    - entity_id: "person.charles"
      prob_given_true: 0.95
      prob_given_false: 0.5
      platform: "state"
      to_state: "home"
    - platform: template
      value_template: {{ today_at("10:00") < now() and now() < today_at("22:00") }}
      prob_given_true: 0.03
      prob_given_false: 0.9
    - platform: template
      value_template: {{ not (today_at("10:00") < now() and now() < today_at("22:00")) }}
      prob_given_true: 0.97
      prob_given_false: 0.1
    - prob_given_true: 0.05
      prob_given_false: 0.5
      platform: "template"
      value_template: '{{ states("person.charles") != "home" }}'
    - entity_id: "light.bedroom_1"
      prob_given_true: 0.1
      prob_given_false: 0.2
      platform: "state"
      to_state: "on"
    - entity_id: "light.bedroom1"
      platform: "state"
      to_state: "off"
      prob_given_false: 0.15
      prob_given_true: 0.8
    - platform: "template"
      value_template: >
        {{
          states('media_player.living_room_tv') == 'playing'
            or
          states('media_player.living_room_tv') == 'paused'
        }}
      prob_given_true: 0.03
      prob_given_false: 0.2
    - platform: "template"
      value_template: >
        {{
          states('media_player.living_room_tv') == 'unavailable'
        }}
      prob_given_true: 0.97
      prob_given_false: 0.8
    - entity_id: "sensor.charles_honor_sleep_confidence"
      prob_given_true: 0.70
      prob_given_false: 0.2
      platform: "numeric_state"
      above: 80
    - entity_id: "sensor.sun"
      prob_given_true: 0.8
      prob_given_false: 0.3
      platform: "state"
      to_state: "below_horizon"
    - prob_given_true: 0.9
      prob_given_false: 0.4
      platform: "template"
      value_template: >
        {% set locked_state = states.binary_sensor.charles_honor_device_locked %}
        {% set bump = now() %}
        {{
          locked_state and locked_state.state == 'on' and (
            as_timestamp(now())
            - as_timestamp(locked_state.last_changed)
          ) > 900
        }}
    - prob_given_true: 0.1
      prob_given_false: 0.6
      platform: "template"
      value_template: >
        {% set locked_state = states.binary_sensor.charles_honor_device_locked %}
        {% set bump = now() %}
        {{
          not (locked_state and locked_state.state == 'on' and (
            as_timestamp(now())
            - as_timestamp(locked_state.last_changed)
          ) > 900)
        }}
