- platform: bayesian
  prior: 0.33
  name: "Gaby Sleeping Bayesian"
  probability_threshold: 0.85
  observations:
    - entity_id: "person.gaby"
      prob_given_true: 0.95
      prob_given_false: 0.5
      platform: "state"
      to_state: "home"
    - entity_id: "light.bedroom_1"
      prob_given_true: 0.01
      prob_given_false: 0.2
      platform: "state"
      to_state: "on"
    - entity_id: "binary_sensor.gaby_phone_untouched"
      prob_given_true: 0.9
      prob_given_false: 0.4
      platform: "state"
      to_state: "on"
    - entity_id: "sensor.gaby_honor_sleep_confidence"
      prob_given_true: 0.90
      prob_given_false: 0.10
      platform: "numeric_state"
      above: 80

    - entity_id: "sensor.sun"
      prob_given_true: 0.7
      prob_given_false: 0.3
      platform: "state"
      to_state: "below_horizon"

- platform: bayesian
  prior: 0.33
  name: "Charles Sleeping Bayesian"
  probability_threshold: 0.85
  observations:
    - entity_id: "person.charles"
      prob_given_true: 0.99
      prob_given_false: 0.5
      platform: "state"
      to_state: "home"
    - entity_id: "light.bedroom_1"
      prob_given_true: 0.1
      prob_given_false: 0.2
      platform: "state"
      to_state: "on"
    - entity_id: "light.bedroom1"
      platform: "state" 
      to_state: "off"
      prob_given_false: 0.15
      prob_given_true: 0.8
    - entity_id: "sensor.charles_honor_sleep_confidence"
      prob_given_true: 0.70
      prob_given_false: 0.2
      platform: "numeric_state"
      above: 80
    - entity_id: "sensor.sun"
      prob_given_true: 0.8
      prob_given_false: 0.3
      platform: "state"
      to_state: "below_horizon"
