GabyPhone:
  name: Gaby's Honor ARP
  mac: 24:6F:8C:0B:6A:02
  icon: mdi:face-woman
  picture:
  track: true

CharlesPhone:
  name: Charles' Pixel ARP
  mac: dc:e5:5b:28:25:8b
  icon: mdi:face
  picture:
  track: true

work_laptop:
  name: Charles work laptop
  mac: CC:48:3A:6E:DB:9B
  icon:
  picture:
 
HarryPhone:
  name: HarryPhone
  mac: A8:CC:6F:02:75:C1
  icon:
  picture:
  track: true

tplink_ap:
  name: TPLINK_AP
  mac: 28:EE:52:B7:5E:40
  icon:
  picture:
  track: true

gaby_phone_bt:
  name: Gabriela's Z Fold3 BT
  mac: BT_C8:BD:4D:34:88:62
  icon:
  picture:
  track: true

charles_phone_bt:
  name: Charles Pixel 6 BT
  mac: BT_DC:E5:5B:28:3C:A9
  icon:
  picture:
  track: true

z8:
  name: Z8
  mac: BT_11:11:22:33:35:37
  icon:
  picture:
  track: true

gardenfairy:
  name: gardenfairy
  mac: C4:DD:57:2B:B0:6D
  icon:
  picture:
  track: true

charles_iphone:
  name: Charles iPhone
  mac: A4:31:35:E2:AE:40
  icon:
  picture:
  track: true

p3:
  name: P3
  mac: BT_2C:E2:D0:B6:FC:8F
  icon:
  picture:
  track: false

uk_4k_android_tv:
  name: UK 4K Android TV
  mac: BT_DC:72:23:1D:10:07
  icon:
  picture:
  track: false

20_df_b9_0a_12_08:
  name: 20_df_b9_0a_12_08
  mac: 20:DF:B9:0A:12:08
  icon:
  picture:
  track: false

30_fd_38_79_93_35:
  name: 30_fd_38_79_93_35
  mac: 30:FD:38:79:93:35
  icon:
  picture:
  track: false

7c_2e_bd_3f_7a_b0:
  name: 7c_2e_bd_3f_7a_b0
  mac: 7C:2E:BD:3F:7A:B0
  icon:
  picture:
  track: false

roborock:
  name: roborock
  mac: 78:11:DC:7E:0F:39
  icon:
  picture:
  track: false

zbook:
  name: ZBook
  mac: 70:9C:D1:A2:23:AD
  icon:
  picture:
  track: false

cblanket:
  name: CBlanket
  mac: B0:4E:26:48:87:A9
  icon:
  picture:
  track: false

homeassistant:
  name: homeassistant
  mac: DC:A6:32:AA:30:0E
  icon:
  picture:
  track: false

office_wired:
  name: office-wired
  mac: 00:E0:4C:36:08:C4
  icon:
  picture:
  track: false

ec_e5_12_00_fe_11:
  name: ec_e5_12_00_fe_11
  mac: EC:E5:12:00:FE:11
  icon:
  picture:
  track: false

gblanket:
  name: GBlanket
  mac: 4C:EB:D6:0F:F1:D5
  icon:
  picture:
  track: false

homeassistant_wifi:
  name: homeassistant_wifi
  mac: DC:A6:32:AA:30:0F
  icon:
  picture:
  track: false

gardenbulb:
  name: GardenBulb
  mac: D8:A0:11:3F:DE:E2
  icon:
  picture:
  track: false

gardenchromecast:
  name: GardenChromecast
  mac: B0:E4:D5:AD:B1:09
  icon:
  picture:
  track: false

googleminigarden:
  name: GoogleMiniGarden
  mac: 38:8B:59:A4:99:1F
  icon:
  picture:
  track: false

f0_6e_0b_3f_8a_bd:
  name: f0_6e_0b_3f_8a_bd
  mac: F0:6E:0B:3F:8A:BD
  icon:
  picture:
  track: false

6c_40_08_b0_f4_d0:
  name: 6c_40_08_b0_f4_d0
  mac: 6C:40:08:B0:F4:D0
  icon:
  picture:
  track: false

bv7100:
  name: BV7100
  mac: BT_EA:5C:46:61:8C:49
  icon:
  picture:
  track: false

ae_f3_a0_a4_14_7b:
  name: ae_f3_a0_a4_14_7b
  mac: AE:F3:A0:A4:14:7B
  icon:
  picture:
  track: false

90_a8_22_ad_65_b1:
  name: 90_a8_22_ad_65_b1
  mac: 90:A8:22:AD:65:B1
  icon:
  picture:
  track: false

ewa_audio_a103:
  name: EWA Audio A103
  mac: BT_30:22:00:00:12:F0
  icon:
  picture:
  track: false

d6_cf_00_0a_68_49:
  name: d6_cf_00_0a_68_49
  mac: D6:CF:00:0A:68:49
  icon:
  picture:
  track: false

96_18_3f_55_eb_f6:
  name: 96_18_3f_55_eb_f6
  mac: 96:18:3F:55:EB:F6
  icon:
  picture:
  track: false

pixel_5:
  name: Pixel 5
  mac: BT_60:B7:6E:09:2A:D2
  icon:
  picture:
  track: false

24_a1_60_1a_3c_0e:
  name: 24_a1_60_1a_3c_0e
  mac: 24:A1:60:1A:3C:0E
  icon:
  picture:
  track: false

2c_26_17_56_e7_f2:
  name: 2c_26_17_56_e7_f2
  mac: 2C:26:17:56:E7:F2
  icon:
  picture:
  track: false

1a_d7_0e_63_de_ee:
  name: 1a_d7_0e_63_de_ee
  mac: 1A:D7:0E:63:DE:EE
  icon:
  picture:
  track: false

70_f7_54_8e_69_2c:
  name: 70_f7_54_8e_69_2c
  mac: 70:F7:54:8E:69:2C
  icon:
  picture:
  track: false

d8_3a_dd_59_92_68:
  name: d8_3a_dd_59_92_68
  mac: D8:3A:DD:59:92:68
  icon:
  picture:
  track: false

f4_30_8b_35_02_9a:
  name: f4_30_8b_35_02_9a
  mac: F4:30:8B:35:02:9A
  icon:
  picture:
  track: false

wf_1000xm4:
  name: WF-1000XM4
  mac: BT_88:C9:E8:CB:26:E4
  icon:
  picture:
  track: false

mk66_id_c8a5:
  name: MK66(ID-C8A5)
  mac: BT_78:02:B7:08:C8:A5
  icon:
  picture:
  track: false

28_cf_da_eb_76_96:
  name: 28_cf_da_eb_76_96
  mac: 28:CF:DA:EB:76:96
  icon:
  picture:
  track: false

oppo_reno5_z:
  name: OPPO Reno5 Z
  mac: BT_60:07:C4:8C:D2:3E
  icon:
  picture:
  track: false

f8_c3_9e_30_dc_e8:
  name: f8_c3_9e_30_dc_e8
  mac: F8:C3:9E:30:DC:E8
  icon:
  picture:
  track: false

oneplus_9_pro_5g:
  name: OnePlus 9 Pro 5G
  mac: BT_D0:49:7C:28:9E:DE
  icon:
  picture:
  track: false

74_74_46_c4_bc_86:
  name: 74_74_46_c4_bc_86
  mac: 74:74:46:C4:BC:86
  icon:
  picture:
  track: false
