GabyPhone:
  name: Gaby's Honor ARP
  mac: 24:6F:8C:0B:6A:02
  icon: mdi:face-woman
  picture:
  track: true

CharlesPhone:
  name: Charles' Pixel ARP
  mac: dc:e5:5b:28:25:8b
  icon: mdi:face
  picture:
  track: true

work_laptop:
  name: Charles work laptop
  mac: CC:48:3A:6E:DB:9B
  icon:
  picture:
 
HarryPhone:
  name: HarryPhone
  mac: A8:CC:6F:02:75:C1
  icon:
  picture:
  track: true

tplink_ap:
  name: TPLINK_AP
  mac: 28:EE:52:B7:5E:40
  icon:
  picture:
  track: true

gaby_phone_bt:
  name: Gabriela's Z Fold3 BT
  mac: BT_C8:BD:4D:34:88:62
  icon:
  picture:
  track: true

charles_phone_bt:
  name: Charles Pixel 6 BT
  mac: BT_DC:E5:5B:28:3C:A9
  icon:
  picture:
  track: true

z8:
  name: Z8
  mac: BT_11:11:22:33:35:37
  icon:
  picture:
  track: true

p3:
  name: P3
  mac: BT_2C:E2:D0:B6:FC:8F
  icon:
  picture:
  track: false

uk_4k_android_tv:
  name: UK 4K Android TV
  mac: BT_DC:72:23:1D:10:07
  icon:
  picture:
  track: false

20_df_b9_0a_12_08:
  name: 20_df_b9_0a_12_08
  mac: 20:DF:B9:0A:12:08
  icon:
  picture:
  track: false

30_fd_38_79_93_35:
  name: 30_fd_38_79_93_35
  mac: 30:FD:38:79:93:35
  icon:
  picture:
  track: false

7c_2e_bd_3f_7a_b0:
  name: 7c_2e_bd_3f_7a_b0
  mac: 7C:2E:BD:3F:7A:B0
  icon:
  picture:
  track: false

roborock:
  name: roborock
  mac: 78:11:DC:7E:0F:39
  icon:
  picture:
  track: false

zbook:
  name: ZBook
  mac: 70:9C:D1:A2:23:AD
  icon:
  picture:
  track: false

cblanket:
  name: CBlanket
  mac: B0:4E:26:48:87:A9
  icon:
  picture:
  track: false

homeassistant:
  name: homeassistant
  mac: DC:A6:32:AA:30:0E
  icon:
  picture:
  track: false

office_wired:
  name: office-wired
  mac: 00:E0:4C:36:08:C4
  icon:
  picture:
  track: false

ec_e5_12_00_fe_11:
  name: ec_e5_12_00_fe_11
  mac: EC:E5:12:00:FE:11
  icon:
  picture:
  track: false

gblanket:
  name: GBlanket
  mac: 4C:EB:D6:0F:F1:D5
  icon:
  picture:
  track: false

homeassistant_wifi:
  name: homeassistant_wifi
  mac: DC:A6:32:AA:30:0F
  icon:
  picture:
  track: false

gardenbulb:
  name: GardenBulb
  mac: D8:A0:11:3F:DE:E2
  icon:
  picture:
  track: false

gardenchromecast:
  name: GardenChromecast
  mac: B0:E4:D5:AD:B1:09
  icon:
  picture:
  track: false

gardenfairy:
  name: gardenfairy
  mac: C4:DD:57:2B:B0:6D
  icon:
  picture:
  track: false

googleminigarden:
  name: GoogleMiniGarden
  mac: 38:8B:59:A4:99:1F
  icon:
  picture:
  track: false
