# Fitbit - see https://www.home-assistant.io/integrations/fitbit/
- platform: fitbit
  clock_format: 12H
  monitored_resources:
    - activities/calories
    - activities/distance
    - activities/elevation
    - activities/floors
    - activities/heart
    - activities/minutesFairlyActive
    - activities/minutesLightlyActive
    - activities/minutesSedentary
    - activities/minutesVeryActive
    - activities/steps
    - sleep/awakeningsCount
    - sleep/efficiency
    - sleep/minutesAfterWakeup
    - sleep/minutesAsleep
    - sleep/minutesAwake
    - sleep/minutesToFallAsleep
    - sleep/startTime
    - sleep/timeInBed