---
# Gaby's Morning Alarm Package
#
# Allows Gaby to set two alarm times and enable/disable the alarm.
# When either alarm triggers, bedroom and hallway lights flash 3 times
# and stay on.
# The alarm is automatically disabled on Fridays at 10:00 AM and
# re-enabled on Sundays at 12:00 PM.
#
# Components:
# - Two input_datetime helpers for alarm time selection
# - input_boolean to enable/disable alarm
# - Two automations (one for each alarm time)
# - Two automations for weekend schedule (disable Friday, enable Sunday)

input_datetime:
  gaby_alarm_time_1:
    name: Gaby's Alarm Time 1
    has_date: false
    has_time: true
    icon: mdi:alarm
  gaby_alarm_time_2:
    name: Gaby's Alarm Time 2
    has_date: false
    has_time: true
    icon: mdi:alarm

input_boolean:
  gaby_alarm_enabled:
    name: Gaby's Alarm Enabled
    icon: mdi:alarm-check

automation:
  - id: '1732500000000'
    alias: Gaby's morning alarm 1
    description: >
      Flash bedroom and hallway lights 3 times and leave on
      when alarm 1 triggers
    triggers:
      - trigger: time
        at: input_datetime.gaby_alarm_time_1
    conditions:
      - condition: state
        entity_id: input_boolean.gaby_alarm_enabled
        state: 'on'
    actions:
      # Flash lights 3 times
      - repeat:
          count: 3
          sequence:
            - action: light.turn_on
              target:
                area_id:
                  - bedroom
                  - hallway
            - delay:
                milliseconds: 1000
            - action: light.turn_off
              target:
                area_id:
                  - bedroom
                  - hallway
            - delay:
                milliseconds: 1000
      # Leave lights on
      - action: light.turn_on
        target:
          area_id:
            - bedroom
            - hallway
    mode: single

  - id: '1732500000001'
    alias: Gaby's morning alarm 2
    description: >
      Flash bedroom and hallway lights 3 times and leave on
      when alarm 2 triggers
    triggers:
      - trigger: time
        at: input_datetime.gaby_alarm_time_2
    conditions:
      - condition: state
        entity_id: input_boolean.gaby_alarm_enabled
        state: 'on'
    actions:
      # Flash lights 3 times
      - repeat:
          count: 3
          sequence:
            - action: light.turn_on
              target:
                area_id:
                  - bedroom
                  - hallway
            - delay:
                milliseconds: 1000
            - action: light.turn_off
              target:
                area_id:
                  - bedroom
                  - hallway
            - delay:
                milliseconds: 1000
      # Leave lights on
      - action: light.turn_on
        target:
          area_id:
            - bedroom
            - hallway
    mode: single

  - id: '1739471156000'
    alias: Gaby's alarm - disable on Friday
    description: >
      Automatically disable alarm every Friday at 10:00 AM
    triggers:
      - trigger: time
        at: '10:00:00'
    conditions:
      - condition: time
        weekday:
          - fri
    actions:
      - action: input_boolean.turn_off
        target:
          entity_id: input_boolean.gaby_alarm_enabled
    mode: single

  - id: '1739471156001'
    alias: Gaby's alarm - enable on Sunday
    description: >
      Automatically enable alarm every Sunday at 12:00 PM
    triggers:
      - trigger: time
        at: '12:00:00'
    conditions:
      - condition: time
        weekday:
          - sun
    actions:
      - action: input_boolean.turn_on
        target:
          entity_id: input_boolean.gaby_alarm_enabled
    mode: single
