---
# Climate Away Mode Package
#
# Two-tier away mode for energy efficiency:
# 1. When anyone leaves home: reduce setpoints by 2°C (mild savings)
# 2. When both are >50km away: turn off completely (maximum savings)
#
# Components:
# - Binary sensor to detect when both people are far away (>50km)
# - Input number helpers to store original setpoint temperatures
# - Automation to reduce setpoints by 2°C when anyone leaves home
# - Automation to restore setpoints when someone returns home
# - Automation to turn off all PID controllers when both far away
# - Automation to turn on PID controllers when someone returns within 50km
#
# Affected climate entities:
# - climate.living_room_trv_pid_controller
# - climate.master_bedroom_trv_pid_controller
# - climate.bedroom_trv_pid_controller

template:
  - binary_sensor:
      - name: "Both Charles and Gaby Far Away"
        unique_id: both_charles_gaby_far_away
        device_class: presence
        state: >
          {% set charles = states.person.charles %}
          {% set gaby = states.person.gaby %}
          {% set home_lat = state_attr('zone.home', 'latitude') %}
          {% set home_lon = state_attr('zone.home', 'longitude') %}

          {# Check if all required data is available #}
          {% if charles.state == 'unavailable' or gaby.state == 'unavailable' %}
            false
          {% elif home_lat is none or home_lon is none %}
            false
          {% else %}
            {# Calculate distances using haversine formula #}
            {% set charles_lat = state_attr('person.charles',
                'latitude') %}
            {% set charles_lon = state_attr('person.charles',
                'longitude') %}
            {% set gaby_lat = state_attr('person.gaby', 'latitude') %}
            {% set gaby_lon = state_attr('person.gaby', 'longitude') %}

            {% if charles_lat is none or charles_lon is none or
                gaby_lat is none or gaby_lon is none %}
              false
            {% else %}
              {% set charles_dist = distance(home_lat, home_lon,
                  charles_lat, charles_lon) %}
              {% set gaby_dist = distance(home_lat, home_lon,
                  gaby_lat, gaby_lon) %}

              {# Both must be more than 50km away #}
              {{ charles_dist > 50 and gaby_dist > 50 }}
            {% endif %}
          {% endif %}

input_number:
  away_mode_living_room_original_temp:
    name: Living Room Original Temperature (Away Mode)
    min: 7
    max: 28
    step: 0.5
    initial: 19
    mode: box

  away_mode_master_bedroom_original_temp:
    name: Master Bedroom Original Temperature (Away Mode)
    min: 7
    max: 28
    step: 0.5
    initial: 19
    mode: box

  away_mode_bedroom_original_temp:
    name: Bedroom Original Temperature (Away Mode)
    min: 7
    max: 28
    step: 0.5
    initial: 19
    mode: box

automation:
  # Automation 1: Reduce setpoints by 2°C when anyone leaves home
  - id: '1736243629001'
    alias: Climate - Reduce setpoints by 2°C when anyone leaves
    description: >
      When anyone leaves home, store current setpoints and reduce them by 2°C
      to save energy while maintaining some heating
    triggers:
      - trigger: state
        entity_id: binary_sensor.anyone_home
        to: 'off'
    conditions: []
    actions:
      # Store original temperatures
      - action: input_number.set_value
        target:
          entity_id: input_number.away_mode_living_room_original_temp
        data:
          value: >
            {{ state_attr('climate.living_room_trv_pid_controller',
               'temperature') | float(19) }}
      - action: input_number.set_value
        target:
          entity_id: input_number.away_mode_master_bedroom_original_temp
        data:
          value: >
            {{ state_attr('climate.master_bedroom_trv_pid_controller',
               'temperature') | float(19) }}
      - action: input_number.set_value
        target:
          entity_id: input_number.away_mode_bedroom_original_temp
        data:
          value: >
            {{ state_attr('climate.bedroom_trv_pid_controller',
               'temperature') | float(19) }}
      # Reduce temperatures by 2°C
      - action: climate.set_temperature
        target:
          entity_id: climate.living_room_trv_pid_controller
        data:
          temperature: >
            {{ [state_attr('climate.living_room_trv_pid_controller',
                'temperature') | float(19) - 2, 7] | max }}
      - action: climate.set_temperature
        target:
          entity_id: climate.master_bedroom_trv_pid_controller
        data:
          temperature: >
            {{ [state_attr('climate.master_bedroom_trv_pid_controller',
                'temperature') | float(19) - 2, 7] | max }}
      - action: climate.set_temperature
        target:
          entity_id: climate.bedroom_trv_pid_controller
        data:
          temperature: >
            {{ [state_attr('climate.bedroom_trv_pid_controller',
                'temperature') | float(19) - 2, 7] | max }}
    mode: single

  # Automation 2: Restore setpoints when someone returns home
  - id: '1736243629002'
    alias: Climate - Restore setpoints when someone returns
    description: >
      When someone returns home, restore the original setpoint temperatures
      that were stored before the reduction
    triggers:
      - trigger: state
        entity_id: binary_sensor.anyone_home
        to: 'on'
    conditions: []
    actions:
      # Restore original temperatures
      - action: climate.set_temperature
        target:
          entity_id: climate.living_room_trv_pid_controller
        data:
          temperature: >
            {{ states('input_number.away_mode_living_room_original_temp')
               | float(19) }}
      - action: climate.set_temperature
        target:
          entity_id: climate.master_bedroom_trv_pid_controller
        data:
          temperature: >
            {{ states('input_number.away_mode_master_bedroom_original_temp')
               | float(19) }}
      - action: climate.set_temperature
        target:
          entity_id: climate.bedroom_trv_pid_controller
        data:
          temperature: >
            {{ states('input_number.away_mode_bedroom_original_temp')
               | float(19) }}
    mode: single

  # Automation 3: Turn off completely when both are far away (>50km)
  - id: '1734631000000'
    alias: Climate - Turn off PID controllers when both far away
    description: >
      When both Charles and Gaby are >50km from home, turn off all PID
      climate controllers to save energy
    triggers:
      - trigger: state
        entity_id: binary_sensor.both_charles_and_gaby_far_away
        to: 'on'
        for:
          minutes: 30
    conditions: []
    actions:
      - action: climate.turn_off
        metadata: {}
        data: {}
        target:
          entity_id:
            - climate.living_room_trv_pid_controller
            - climate.master_bedroom_trv_pid_controller
            - climate.bedroom_trv_pid_controller
    mode: single

  # Automation 4: Turn on when someone returns within 50km
  - id: '1734631000001'
    alias: Climate - Turn on PID controllers when someone returns
    description: >
      When at least one of Charles or Gaby comes within 50km of home,
      turn PID controllers back on
    triggers:
      - trigger: state
        entity_id: binary_sensor.both_charles_and_gaby_far_away
        to: 'off'
    conditions: []
    actions:
      - action: climate.turn_on
        metadata: {}
        data: {}
        target:
          entity_id:
            - climate.living_room_trv_pid_controller
            - climate.master_bedroom_trv_pid_controller
            - climate.bedroom_trv_pid_controller
    mode: single
