---
# Climate Away Mode Package
#
# Automatically reduces PID climate controller setpoints by 2째C when everyone
# is away from home, and restores them when someone returns.
#
# Components:
# - Input number helpers to store original setpoint temperatures
# - Automation to reduce setpoints by 2째C when everyone leaves
# - Automation to restore original setpoints when someone returns
#
# Affected climate entities:
# - climate.living_room_trv_pid_controller
# - climate.master_bedroom_trv_pid_controller
# - climate.bedroom_trv_pid_controller

input_number:
  away_mode_living_room_original_temp:
    name: Living Room Original Temperature (Away Mode)
    min: 7
    max: 28
    step: 0.5
    initial: 19
    mode: box

  away_mode_master_bedroom_original_temp:
    name: Master Bedroom Original Temperature (Away Mode)
    min: 7
    max: 28
    step: 0.5
    initial: 19
    mode: box

  away_mode_bedroom_original_temp:
    name: Bedroom Original Temperature (Away Mode)
    min: 7
    max: 28
    step: 0.5
    initial: 19
    mode: box

automation:
  - id: '1734631000000'
    alias: Climate - Reduce setpoints when everyone away
    description: >
      When everyone leaves home, store current setpoints and reduce them by 2째C
      to save energy while maintaining some heating
    triggers:
      - trigger: state
        entity_id: binary_sensor.anyone_home
        to: 'off'
        for:
          minutes: 30
    conditions: []
    actions:
      # Store original temperatures
      - action: input_number.set_value
        target:
          entity_id: input_number.away_mode_living_room_original_temp
        data:
          value: "{{ state_attr('climate.living_room_trv_pid_controller', 'temperature') | float(19) }}"
      - action: input_number.set_value
        target:
          entity_id: input_number.away_mode_master_bedroom_original_temp
        data:
          value: "{{ state_attr('climate.master_bedroom_trv_pid_controller', 'temperature') | float(19) }}"
      - action: input_number.set_value
        target:
          entity_id: input_number.away_mode_bedroom_original_temp
        data:
          value: "{{ state_attr('climate.bedroom_trv_pid_controller', 'temperature') | float(19) }}"
      # Reduce temperatures by 2째C
      - action: climate.set_temperature
        target:
          entity_id: climate.living_room_trv_pid_controller
        data:
          temperature: "{{ [state_attr('climate.living_room_trv_pid_controller', 'temperature') | float(19) - 2, 7] | max }}"
      - action: climate.set_temperature
        target:
          entity_id: climate.master_bedroom_trv_pid_controller
        data:
          temperature: "{{ [state_attr('climate.master_bedroom_trv_pid_controller', 'temperature') | float(19) - 2, 7] | max }}"
      - action: climate.set_temperature
        target:
          entity_id: climate.bedroom_trv_pid_controller
        data:
          temperature: "{{ [state_attr('climate.bedroom_trv_pid_controller', 'temperature') | float(19) - 2, 7] | max }}"
    mode: single

  - id: '1734631000001'
    alias: Climate - Restore setpoints when someone returns
    description: >
      When someone returns home, restore the original setpoint temperatures
      that were stored before the reduction
    triggers:
      - trigger: state
        entity_id: binary_sensor.anyone_home
        to: 'on'
    conditions: []
    actions:
      # Restore original temperatures
      - action: climate.set_temperature
        target:
          entity_id: climate.living_room_trv_pid_controller
        data:
          temperature: "{{ states('input_number.away_mode_living_room_original_temp') | float(19) }}"
      - action: climate.set_temperature
        target:
          entity_id: climate.master_bedroom_trv_pid_controller
        data:
          temperature: "{{ states('input_number.away_mode_master_bedroom_original_temp') | float(19) }}"
      - action: climate.set_temperature
        target:
          entity_id: climate.bedroom_trv_pid_controller
        data:
          temperature: "{{ states('input_number.away_mode_bedroom_original_temp') | float(19) }}"
    mode: single
