---
# Master Bedroom Climate Control Package
#
# PID-controlled TRV system for master bedroom heating.
# Uses external temperature sensor and smart_thermostat integration.
#
# Components:
# - PID controller climate entity
# - Helper for valve position (0-100)
# - Valve position sync automation (blueprint)
# - External sensor sync automation (blueprint)
# - Bidirectional setpoint sync (physical TRV ↔ PID controller)
# - One-time 4am heating restart automation (self-disabling)
#
# Physical device: climate.trv_master_bedroom
# External sensor: sensor.sensor_master_bedroom_temperature
#
# Blueprints used:
# - arnie580/sonoff-trv-pid.yaml
# - photomoose/sonoff-trvzb-external-temperature-sensor-calibration.yaml

input_number:
  master_bedroom_trv_valve_position:
    name: Master bedroom TRV Valve Position
    initial: 0
    min: 0
    max: 100
    step: 1

input_boolean:
  boost_mode_master_bedroom:
    name: Boost Mode - Master Bedroom
    icon: mdi:rocket-launch
    initial: false

input_datetime:
  boost_start_master_bedroom:
    name: Boost Start - Master Bedroom
    has_date: true
    has_time: true
    icon: mdi:clock-start

button:
  - platform: template
    buttons:
      boost_master_bedroom:
        unique_id: boost_button_master_bedroom
        friendly_name: "Boost Master Bedroom"
        icon_template: mdi:rocket-launch
        press:
          - action: input_boolean.toggle
            target:
              entity_id: input_boolean.boost_mode_master_bedroom

climate:
  - platform: smart_thermostat
    name: Master bedroom TRV PID controller
    unique_id: trv_pid_master_bedroom
    heater: input_number.master_bedroom_trv_valve_position
    target_sensor: sensor.sensor_master_bedroom_temperature
    min_temp: 7
    max_temp: 28
    ac_mode: False
    target_temp: 19
    keep_alive:
      seconds: 60
    kp: 60
    ki: 0.01
    kd: 2000
    pwm: 0

automation:
  - id: '1761691019775'
    alias: Master bedroom TRV - sync valve with helper
    description: 'Copy the settings from the 0 - 100 helper to the TRV valve position.
      This will be controlled by a PID controller from Smart thermostat (PID) - see
      the YAML. '
    use_blueprint:
      path: arnie580/sonoff-trv-pid.yaml
      input:
        thermostat_value: input_number.master_bedroom_trv_valve_position
        max_valve_opening: number.trv_master_bedroom_valve_opening_degree
        max_valve_closing: number.trv_master_bedroom_valve_closing_degree

  - id: '1761479998275'
    alias: Sync master bedroom TRV with external sensor
    description: ''
    use_blueprint:
      path: photomoose/sonoff-trvzb-external-temperature-sensor-calibration.yaml
      input:
        external_temperature_sensor: sensor.sensor_master_bedroom_temperature
        trv_external_temperature_input:
        - number.trv_master_bedroom_external_temperature_input

  - id: '1732372800002'
    alias: Master bedroom TRV - sync physical setpoint to PID
    description: 'When user changes setpoint on physical TRV, copy it to the PID controller'
    triggers:
    - trigger: state
      entity_id: climate.trv_master_bedroom
      attribute: temperature
    conditions:
    - condition: template
      value_template: >
        {% set trv_temp = state_attr('climate.trv_master_bedroom', 'temperature') %}
        {% set pid_temp = state_attr('climate.master_bedroom_trv_pid_controller', 'temperature') %}
        {{ trv_temp != none and pid_temp != none and trv_temp != pid_temp }}
    actions:
    - action: climate.set_temperature
      metadata: {}
      data:
        temperature: >
          {{ state_attr('climate.trv_master_bedroom', 'temperature') }}
      target:
        entity_id: climate.master_bedroom_trv_pid_controller
    mode: single

  - id: '1732372800003'
    alias: Master bedroom TRV - sync PID setpoint to physical
    description: 'When user changes setpoint on PID controller, copy it to the physical TRV'
    triggers:
    - trigger: state
      entity_id: climate.master_bedroom_trv_pid_controller
      attribute: temperature
    conditions:
    - condition: template
      value_template: >
        {% set trv_temp = state_attr('climate.trv_master_bedroom', 'temperature') %}
        {% set pid_temp = state_attr('climate.master_bedroom_trv_pid_controller', 'temperature') %}
        {{ trv_temp != none and pid_temp != none and trv_temp != pid_temp }}
    actions:
    - action: climate.set_temperature
      metadata: {}
      data:
        temperature: >
          {{ state_attr('climate.master_bedroom_trv_pid_controller', 'temperature') }}
      target:
        entity_id: climate.trv_master_bedroom
    mode: single

  - id: '1763508383336'
    alias: Master bedroom restart heating at 4am
    description: ''
    triggers:
    - trigger: time
      at: 04:00:00
    conditions: []
    actions:
    - action: climate.set_temperature
      metadata: {}
      data:
        temperature: 22
        hvac_mode: heat
      target:
        entity_id: climate.master_bedroom_trv_pid_controller
    - action: automation.turn_off
      metadata: {}
      data:
        stop_actions: false
      target:
        entity_id: automation.master_bedroom_restart_heating_at_4am
    mode: single

  - id: '1736044800003'
    alias: Master bedroom TRV - activate boost mode
    description: 'When boost mode is activated, set valve to 100% and stop PID updates'
    triggers:
    - trigger: state
      entity_id: input_boolean.boost_mode_master_bedroom
      to: 'on'
    conditions: []
    actions:
    - action: input_datetime.set_datetime
      target:
        entity_id: input_datetime.boost_start_master_bedroom
      data:
        timestamp: '{{ now().timestamp() }}'
    - action: automation.turn_off
      target:
        entity_id: automation.master_bedroom_trv_sync_valve_with_helper
      data:
        stop_actions: false
    - action: input_number.set_value
      target:
        entity_id: input_number.master_bedroom_trv_valve_position
      data:
        value: 100
    - action: climate.set_hvac_mode
      target:
        entity_id: climate.master_bedroom_trv_pid_controller
      data:
        hvac_mode: 'off'
    mode: single

  - id: '1736044800004'
    alias: Master bedroom TRV - deactivate boost mode
    description: 'When boost mode is turned off, restore PID control'
    triggers:
    - trigger: state
      entity_id: input_boolean.boost_mode_master_bedroom
      to: 'off'
    conditions: []
    actions:
    - action: automation.turn_on
      target:
        entity_id: automation.master_bedroom_trv_sync_valve_with_helper
    - action: climate.set_hvac_mode
      target:
        entity_id: climate.master_bedroom_trv_pid_controller
      data:
        hvac_mode: 'heat'
    mode: single

  - id: '1736044800005'
    alias: Master bedroom TRV - boost timeout
    description: 'Turn off boost mode after 1 hour'
    triggers:
    - trigger: time_pattern
      minutes: /5
    conditions:
    - condition: state
      entity_id: input_boolean.boost_mode_master_bedroom
      state: 'on'
    - condition: template
      value_template: >
        {% set boost_start = states('input_datetime.boost_start_master_bedroom') %}
        {% if boost_start not in ['unknown', 'unavailable', ''] %}
          {% set start_time = as_timestamp(boost_start) %}
          {% set current_time = now().timestamp() %}
          {{ (current_time - start_time) >= 3600 }}
        {% else %}
          false
        {% endif %}
    actions:
    - action: input_boolean.turn_off
      target:
        entity_id: input_boolean.boost_mode_master_bedroom
    mode: single
