---
# Kitchen Motion Lighting Package
#
# Controls kitchen lights based on motion sensor with manual override.
# Night mode: only surface lights turn on. All lights always turn off.
# Button left press toggles motion control, right press toggles surface lights.
# Switch LED syncs with motion control state.
#
# Devices:
# - Kitchen switch (motion control): bb9532358b487e4b89cfe0e3b76b91e0
# - Kitchen surface lights switch: f4b4e900064fe24bcc24ab77d53af88a
#
# Referenced by:
# - scene.pause_mode (1746979065248)
# - scene.spot_1 (1746982175127)
# - scene.spot_2 (1746982545091)

input_boolean:
  kitchen_motion_enabled:
    name: Kitchen Motion Enabled
    icon: mdi:motion-sensor
    initial: true

automation:
  - id: '1742137223032'
    alias: Kitchen motion
    description: ''
    triggers:
    - trigger: state
      entity_id: binary_sensor.motion_sensor_kitchen_occupancy
      from: 'off'
      to: 'on'
    - trigger: state
      entity_id:
      - input_boolean.kitchen_motion_enabled
      to: 'on'
    conditions:
    - condition: state
      entity_id: input_boolean.kitchen_motion_enabled
      state: 'on'
    - condition: state
      entity_id: binary_sensor.motion_sensor_kitchen_occupancy
      state: 'on'
    actions:
    - if:
      - condition: state
        entity_id: input_boolean.night_mode
        state: 'on'
      then:
        - alias: Turn on only surface lights in night mode
          action: light.turn_on
          target:
            entity_id: light.kitchen_surface_lights
          data: {}
      else:
        - alias: Turn on all kitchen lights
          action: light.turn_on
          target:
            area_id: kitchen
          data: {}
    - alias: Wait until there is no motion from device
      wait_for_trigger:
        trigger: state
        entity_id: binary_sensor.motion_sensor_kitchen_occupancy
        from: 'on'
        to: 'off'
    - alias: Wait the number of seconds that has been set
      delay: 300
    - alias: Turn off all kitchen lights
      action: light.turn_off
      target:
        area_id: kitchen
      data: {}
    mode: restart
    max_exceeded: silent

  - id: '1745325342231'
    alias: Kitchen motion controlled by switch
    description: ''
    triggers:
    - domain: mqtt
      device_id: bb9532358b487e4b89cfe0e3b76b91e0
      type: action
      subtype: single_left
      trigger: device
    conditions: []
    actions:
    - action: input_boolean.toggle
      metadata: {}
      data: {}
      target:
        entity_id: input_boolean.kitchen_motion_enabled
    mode: single

  - id: '1745327309760'
    alias: Kitchen switch update with motion state
    description: ''
    triggers:
    - trigger: state
      entity_id:
      - input_boolean.kitchen_motion_enabled
      for:
        hours: 0
        minutes: 0
        seconds: 5
    conditions: []
    actions:
    - if:
      - condition: state
        entity_id: input_boolean.kitchen_motion_enabled
        state: 'on'
      then:
      - type: turn_on
        device_id: bb9532358b487e4b89cfe0e3b76b91e0
        entity_id: 8afbce029373c30cdf50bb2f317faee5
        domain: switch
      else:
      - type: turn_off
        device_id: bb9532358b487e4b89cfe0e3b76b91e0
        entity_id: 8afbce029373c30cdf50bb2f317faee5
        domain: switch
    mode: restart

  - id: '1745327896846'
    alias: Kitchen button controls surface lights
    description: ''
    triggers:
    - domain: mqtt
      device_id: bb9532358b487e4b89cfe0e3b76b91e0
      type: action
      subtype: single_right
      trigger: device
    conditions: []
    actions:
    - if:
      - condition: device
        type: is_on
        device_id: bb9532358b487e4b89cfe0e3b76b91e0
        entity_id: 81a39d335fe37927b2849f2eef94b6ed
        domain: light
      then:
      - type: turn_on
        device_id: f4b4e900064fe24bcc24ab77d53af88a
        entity_id: 97c5afcebb430bd9c36137a010c70301
        domain: switch
      else:
      - type: turn_off
        device_id: f4b4e900064fe24bcc24ab77d53af88a
        entity_id: 97c5afcebb430bd9c36137a010c70301
        domain: switch
    mode: single
